### ISSUE TITLE
can you provide the file "Adapting OpenFOAM for massively parallel GPU architecture"

### ISSUE THREAD

**Issue by femmech** [Atizar/RapidCFD-dev#10]
hello, daniel jasinski

when I serch the gpu implement in openfoam, I found your lecture "Adapting OpenFOAM for massively parallel GPU architecture" at this website https://www.esi-group.com/resources/abstract-openfoam2015-jasinski-atizar-adapting-openfoam-massively-parallel-gpu-architecture

however, I cannot found the whole file. Instead, only the abstract can found on the internet. 
I cannot understand the RapidCFD  clearly. Maybe the file can help me understand the RapidCFD, I would appreciate if you provide the whole file of the lecture.
thank you!

**Comment by daniel-jasinski** [comment]
Please contact me on my email and I will send you the file.
