### ISSUE TITLE
compile errors

### ISSUE THREAD

**Issue by Benjamin-git** [Atizar/RapidCFD-dev#11]
Hi, I have tried several times to compile the rapidCFD, but I encountered many mistakes

1.the first error, when I use the thirdParty from the RapidCFD provide, I met this problem
A fatal error,mpi.h： without the file or directory
but I replace the thridParty with openfoam provide, the thirdParty compiled, I don't whether it will affect mulit-GPUs though I only have one GPU now
2. the second error, at the first time, I used cuda7.5 and gcc 4.8.3, I have success compiled the RapidCFD, but when I run icoFoam from RapidCFD, it cannot run, and said segment error(core dumped)
3.the third error, when I met the second error, I uninstall cuda7.5 replace with cuda7.0 (my computer is centos 7.1 which don't support cuda6.5), 
I use this follow command to compile rapidCFD
cd ~/RapidCFD/RapidCFD-dev
echo "alias rapid='source \$HOME/RapidCFD/RapidCFD-dev/etc/bashrc'" >> $HOME/.bashrc
export WM_SCHEDULER=wmakeScheduler 
export WM_HOSTS="mypc:8" 
export WM_NCOMPPROCS=$($WM_SCHEDULER -count) 
export WM_COLOURS="black blue green cyan red magenta yellow" 
./Allwmake | tee log.wmake
but I just cannot compile it......
4. the forth error, then I tried to install RapidCFD at /opt/RapidCFD
still failed

would you provide the detail install method?

**Comment by Benjamin-git** [comment]
when I run rapidCFD icoFoam in cavity, it said 
terminate called after throwing an intance of 'thrust:: system::system_error' 
what (): cudaEventSynchronize in future::wait: an illegal memory access was encountered

can someone successful compile the RapidCFD help me solve the compile problem 
thank you~
best regards,
Benjamin

**Comment by daniel-jasinski** [comment]
Hello Benjamin,

Could you run cuda-memcheck on icoFoam to see where exactly this error occures?

Daniel

**Comment by Benjamin-git** [comment]
I use this command $cuda-memcheck icoFoam, and I get this 
[log.cudamemcheck.icoFoam.txt](https://github.com/Atizar/RapidCFD-dev/files/39988/log.cudamemcheck.icoFoam.txt)


========= Error: process didn't terminate successfully
========= Internal error (20)
========= No CUDA-MEMCHECK results found

sigh......
