### ISSUE TITLE
what's the optimal setting of GAMG in gpu?

### ISSUE THREAD

**Issue by samech-git** [Atizar/RapidCFD-dev#17]
Dear Daniel,
In sim-flow website it says that GAMG is faster than DIC/DILU preconditoner, but I in my testing it was slower than AINV preconditioner in RapidCFD by 1.27x in 100 time step, this my GAMG setting: 
     p 
    {
        solver GAMG; 
        tolerance 1e-06; 
        relTol 0; 
        smoother GaussSeidel; 
        nPreSweeps 0;
        nPostSweeps 2;
        nFinestSweeps 2;
        cacheAgglomeration true;
        nCellsInCoarsestLevel 10;
        agglomerator faceAreaPair;
        mergeLevels 1;
    }
it slower than AINV precondioner by 1.27x, Is it convenience for you to post your GAMG setting in this thread [https://sim-flow.com/rapid-cfd-gpu/](url) (LES case)? Is there a different optimal setting in RC compare with openfoam?

Benjamin,
Best Reagrads.

**Comment by daniel-jasinski** [comment]
Hello Benjamin,

What was the solver you were using?

The performance is very much dependent on the size of the mesh. 

RC and OF setting should in most cases be the same. However sometimes RC works better with higher values of nCellsInCoarsestLevel. Typically some value between 10 and 10000 should be optimal.

Daniel

**Comment by Benjamin-git** [comment]
I test a solver written by myself.
I changed nCellsInCoarsestLevel from 10 to 1000, but clockTime almost does not change. I will test my solver more times.
Thanks you!
