### ISSUE TITLE
Multi-GPU for different nodes?

### ISSUE THREAD

**Issue by pieterMoorsDiabatix** [Atizar/RapidCFD-dev#24]
Hi, I am currently working on an HPC cluster. Is it possible in RapidCFD to run a simulation on multiple GPUs who are located on different nodes?

**Comment by daniel-jasinski** [comment]
You can run RC on multiple GPUs on different nodes. You just need to provide mapping from MPI rank to CUDA device ID on a particular node. You can do it using **-devices** argument.
Example: You want to run **simpleFoam**  on four GPUs spread across two nodes. The first node will host MPI ranks 0 and 2, the second node will host ranks 1 and 3. Then your command line argument should look like this:

**mpirun -np 4 -hosts ...  simpleFoam -parallel -devices "(0 0 1 1)"**

The list after **-devices** tells RC to use devices with ID 0 for ranks 0 and 1, and devices with ID 1 for ranks 2 and 3.

**Comment by Dcn303** [comment]
> 

Sir
i have 10 nodes each having 2GPUs
now i would like to run **simpleFoam** command in this 10 nodes (10x2=20 gpus) then how exactly would i write the command **simpleFoam**
Please help in this regard 
Thank you sir

**Comment by TonkomoLLC** [comment]
I think this is done as follows. Note `node#Name` refers to the computer name or IP address of your node.

contents of the file `machines`

```
node1Name cpu=2
node2Name cpu=2
.
.
node10Name cpu=2
```

decompose your case (decomposeParDict) for 20 processors.

Then, supposing your GPU's on each of the computers listed in the machines file are numbers 0 and 1:


```
mpirun -np 20 -hostfile machines interFoam -parallel -devices "(0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1)"
```

I have never tried this exact procedure before. I hope there are no errors in my notation.

**Comment by TonkomoLLC** [comment]
```
Sir here in your above message did you meant

node1Name gpu=2
node2Name gpu=2
..
.
node10Name gpu=2
```

I think I am correct with using the terminology `cpu`

**Comment by Dcn303** [comment]
> I think this is done as follows. Note `node#Name` refers to the computer name or IP address of your node.
> 
> contents of the file `machines`
> 
> ```
> node1Name cpu=2
> node2Name cpu=2
> .
> .
> node10Name cpu=2
> ```
> 
> decompose your case (decomposeParDict) for 20 processors.
> 
> Then, supposing your GPU's on each of the computers listed in the machines file are numbers 0 and 1:
> 
> ```
> mpirun -np 20 -hostfile machines interFoam -parallel -devices "(0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1)"
> ```
> 
> I have never tried this exact procedure before. I hope there are no errors in my notation.

Sir 
just for clearification 
```
node1Name gpu=2
node2Name gpu=2
.
.
node10Name gpu=2
```
and sir is the `machines`a text file ? where it will contain the IP address of my node where each line by line 
of this file will have ip address of each node 
sorry for my high level of ignorance sir :-)

**Comment by TonkomoLLC** [comment]
Yes, `machines` is a text file.

It is the same procedure for running CPU OpenFOAM with multiple nodes. Se, for example, [Section 3.2.2 of this website](https://www.openfoam.com/documentation/user-guide/3-running-applications/3.2-running-applications-in-parallel)

**Comment by Dcn303** [comment]
> Yes, `machines` is a text file.
> 
> It is the same procedure for running CPU OpenFOAM with multiple nodes. Se, for example, [Section 3.2.2 of this website](https://www.openfoam.com/documentation/user-guide/3-running-applications/3.2-running-applications-in-parallel)

Thank you so much sir i will look into it
