### ISSUE TITLE
Assigning jobs to different GPUs

### ISSUE THREAD

**Issue by KingKraut** [Atizar/RapidCFD-dev#28]
I managed compiling my custom application and transport and turbulence models. However, I did not yet manage to compile swak4Foam with RapidCFD, which would be nice, too. But for now, this is fully sufficient and I am very happy with the performance on one GPU! =)

But as I have two Tesla K80 at hand I wanted to ask, if there is a possibility from within RapidCFD, with which I can assign a job to a certain GPU. I do not want to have simultaneous jobs running on the same GPU, but distribute them... Similiar to running a decomposed case with the normal OpenFOAM-Distribution and assigning certain machines on which to run the processes...
Is there any such thing implemented in RapidCFD or do I need to assign this before submitting a job from within RapidCFD?

I hope my question is clear enough?!

Thanks a lot for any hints!
Johannes

**Comment by daniel-jasinski** [comment]
If you run RC in parallel, it will try to map each MPI rank to a different device. For example if you have two GPUs and run your case in parallel using two MPI processes, the first process will use the first device and the second process will use the second device.

Do you require a more advanced configuration?

**Comment by KingKraut** [comment]
Thanks a lot for the reply! 
I have not yet tried running a decomposed case, but from one of the other threads I think this will be done with "mpirun -np #gpus pisoFoam -parallel", right?

My question was rather if I can assign a serial simulation run to a certain gpu. Right now I have 3 simulation runs started, which all run on the same single gpu. I don't know if this influences the performance, but just to equally distribute the load I was thinking about how to distribute serial jobs to single gpus. Does this make sense?

Nonetheless, thanks for the advice. I will try a decomposed case soon enough, too!!
Best regards

**Comment by daniel-jasinski** [comment]
Ok, now I understand.
To tell RC which GPU to use you need to pass additional parameter **-device** with ID of the device to use, e.g.:
**simpleFoam -device 1**

**Comment by KingKraut** [comment]
Thanks a lot for the answer. That was exaclty, what I meant and it works fine!
Sorry, if my question was a bit muddled before!
