### ISSUE TITLE
running RCFD in parallel

### ISSUE THREAD

**Issue by KingKraut** [Atizar/RapidCFD-dev#30]
Dear all,

finally I got through to actually trying running RCFD in parallel on 2 gpus!
I loaded openmpi (vs 1.8.4), which is located in the /opt/RapidCFD/ThirdParty-dev/openmpi-1.8.4, where it should be installed according to [here](https://github.com/Atizar/RapidCFD-dev/wiki/Install)
I ran 
> mpirun -np 2 pisoFoam -parallel

and got the following error message:

> --> FOAM FATAL ERROR: 
> Trying to use the dummy Pstream library.
> This dummy library cannot be used in parallel mode
> 
>     From function UPstream::init(int& argc, char**& argv)
>     in file UPstream.C at line 37.
> 
> FOAM exiting
> 
> 
> 
> --> FOAM FATAL ERROR: 
> Trying to use the dummy Pstream library.
> This dummy library cannot be used in parallel mode
> 
>     From function UPstream::init(int& argc, char**& argv)
>     in file UPstream.C at line 37.
> 
> FOAM exiting
> 
> -------------------------------------------------------
> Primary job  terminated normally, but 1 process returned
> a non-zero exit code.. Per user-direction, the job has been aborted.
> -------------------------------------------------------
> --------------------------------------------------------------------------
> mpirun detected that one or more processes exited with non-zero status, thus causing
> the job to be terminated. The first process to do so was:
> 
>   Process name: [[6656,1],0]
>   Exit code:    1
> --------------------------------------------------------------------------
> 

Can you tell me, what I have done wrong?

I fear it might be, that I have not considered the WM_NCOMPROCS variable in the build process of RapidCFD...?
Can this be fixed afterwards somehow without recompiling all?

Thanks a lot for all hints!!

Best regards
Johannes

PS: sorry, for the changes in font size, don't know, where this came from...

**Comment by daniel-jasinski** [comment]
Hello,

The WM_NCOMPPROCS variable does not influence the resulting binaries only the compilation speed.

The error indicates that the libPstream.so library that uses MPI was not compiled. You can force build of this library by running

**wmake libso src/Pstream/mpi**

command in the RapidCFD-dev directory.

If it compiles without errors, the reported error should disappear.

Best regards,
Daniel

**Comment by KingKraut** [comment]
Thanks a lot for the fast response.
I tried as you suggested, however, get the following error message:

> SOURCE=UOPwrite.C ;  nvcc -Xptxas -dlcm=cg -m64 -arch=sm_30 -Dlinux64 -DWM_DP -Xcompiler -Wall -Xcompiler -Wextra -Xcompiler -Wno-unused-parameter -Xcompiler -Wno-vla -Xcudafe "--diag_suppress=null_reference" -Xcudafe "--diag_suppress=subscript_out_of_range" -Xcudafe "--diag_suppress=extra_semicolon" -Xcudafe "--diag_suppress=partial_override" -Xcudafe "--diag_suppress=implicit_return_from_non_void_function" -Xcudafe "--diag_suppress=virtual_function_decl_hidden" -O3  -DNoRepository -D__RESTRICT__='__restrict__'    -IlnInclude -I. -I/opt/RapidCFD/RapidCFD-dev/src/OpenFOAM/lnInclude -I/opt/RapidCFD/RapidCFD-dev/src/OSspecific/POSIX/lnInclude   -Xcompiler -fPIC -x cu -D__HOST____DEVICE__='__host__ __device__' -o Make/linux64NvccDPOpt/UOPwrite.o -c $SOURCE
> UOPwrite.C:29:17: fatal error: mpi.h: No such file or directory
>  #include "mpi.h"
>                  ^
> compilation terminated.
> make: *** [Make/linux64NvccDPOpt/UOPwrite.o] Error 1

mpi.h is missing.
I guess it is not properly included beforehand...
I will go and have a look, where to find it...
If you can give me any hints, how to quickly fix this, thanks a lot in advance.

Best regards
JOhannes

**Comment by daniel-jasinski** [comment]
There is a special build script for building Pstream library that needs to be called. To do this go to the _src/Pstream_ directory and invoke **./Allwmake**. This should setup proper compiler search paths.

**Comment by KingKraut** [comment]
Thanks for the advice.
This command tells me

> + wmake libso dummy
> '/opt/RapidCFD/RapidCFD-dev/platforms/linux64NvccDPOpt/lib/dummy/libPstream.so' is up to date.
> + case "$WM_MPLIB" in

Do I need to add another in the Allwmake, maybe?

**Comment by daniel-jasinski** [comment]
Could you check what is the value of this environment variables in your terminal:
WM_MPLIB
FOAM_MPI

**Comment by KingKraut** [comment]
Thanks for the question.
I was just looking at just that =)

echo $FOAM_MPI gives dummy
echo $WM_MPLIB gives /opt/RapidCFD/ThirdParty-dev/openmpi-1.8.4-cuda/

**Comment by daniel-jasinski** [comment]
In your _etc/bashrc_ file, how does the line starting with **export WM_MPLIB=** look like?

**Comment by KingKraut** [comment]
In the bashrc I have the following:

> export PATH="$PATH:/opt/RapidCFD/ThirdParty-dev/openmpi-1.8.4-cuda/bin"
> export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/opt/RapidCFD/ThirdParty-dev/openmpi-1.8.4-cuda/lib/"
> alias RCFD='source /opt/RapidCFD/RapidCFD-dev/etc/bashrc foamCompiler=system **WM_MPLIB=/opt/RapidCFD/ThirdParty-dev/openmpi-1.8.4-cuda/**; scl enable devtoolset-3 bash'

Does it make a difference if the WM_MPLIB is exported separately?

**Comment by daniel-jasinski** [comment]
It is not that it is exported separately, the thing is that WM_MPLIB does not suppose to hold the path to the MPI library, only the type of the library which is later used to set up other environment variables and compiler search paths.

To repair your setup, remove all your custom modifications of WM_MPLIB in _bashrc_ and leave it with the default value **export WM_MPLIB=OPENMPI**. Then find this line **export FOAM_MPI=openmpi-1.8.4** in your _etc/config/settings.sh_ file and change it to **export FOAM_MPI=openmpi-1.8.4-cuda**. Then source again the _bashrc_ file.

**Comment by KingKraut** [comment]
Thanks for the explanation!

I did as you suggested, however, now I get the first error again: mpi.h is missing

> + wmake libso dummy
> '/opt/RapidCFD/RapidCFD-dev/platforms/linux64NvccDPOpt/lib/dummy/libPstream.so' is up to date.
> + case "$WM_MPLIB" in
> + set +x
> 
> Note: ignore spurious warnings about missing mpicxx.h headers
> 
> wclean mpi
> wmake libso mpi
> wmakeLnInclude: linking include files to ./lnInclude
> Making dependency list for source file UOPwrite.C
> could not open file mpi.h for source file UOPwrite.C due to No such file or directory
> Making dependency list for source file UIPread.C
> could not open file mpi.h for source file UIPread.C due to No such file or directory
> Making dependency list for source file UPstream.C
> could not open file mpi.h for source file UPstream.C due to No such file or directory
> Making dependency list for source file PstreamGlobals.C
> could not open file mpi.h for source file PstreamGlobals.C due to No such file or directory
> SOURCE=UOPwrite.C ;  nvcc -Xptxas -dlcm=cg -m64 -arch=sm_30 -Dlinux64 -DWM_DP -Xcompiler -Wall -Xcompiler -Wextra -Xcompiler -Wno-unused-parameter -Xcompiler -Wno-vla -Xcudafe "--diag_suppress=null_reference" -Xcudafe "--diag_suppress=subscript_out_of_range" -Xcudafe "--diag_suppress=extra_semicolon" -Xcudafe "--diag_suppress=partial_override" -Xcudafe "--diag_suppress=implicit_return_from_non_void_function" -Xcudafe "--diag_suppress=virtual_function_decl_hidden" -O3  -DNoRepository -D__RESTRICT__='__restrict__'  -DOMPI_SKIP_MPICXX -I/opt/RapidCFD/ThirdParty-dev/platforms/linux64Nvcc/openmpi-1.8.4-cuda/include -IlnInclude -I. -I/opt/RapidCFD/RapidCFD-dev/src/OpenFOAM/lnInclude -I/opt/RapidCFD/RapidCFD-dev/src/OSspecific/POSIX/lnInclude   -Xcompiler -fPIC -x cu -D__HOST____DEVICE__='__host__ __device__' -o Make/linux64NvccDPOptOPENMPI/UOPwrite.o -c $SOURCE
> UOPwrite.C:29:17: fatal error: mpi.h: No such file or directory
>  #include "mpi.h"
>                  ^
> compilation terminated.
> make: *** [Make/linux64NvccDPOptOPENMPI/UOPwrite.o] Error 1

mpi.h is missing...

**Comment by daniel-jasinski** [comment]
You probably "manually" compiled your OpenMPI and the directory structure is different from what OpenFOAM expects. You can repair this by creating symbolic link **/opt/RapidCFD/ThirdParty-dev/platforms/linux64Nvcc/openmpi-1.8.4-cuda/include** that points to your OpenMPI include directory.

**Comment by KingKraut** [comment]
Thanks a lot again for all the help!!

I did as you suggested und it went a little further - until the next error occured:

> /opt/rh/devtoolset-3/root/usr/libexec/gcc/x86_64-redhat-linux/4.9.2/ld: cannot find -lmpi
> collect2: error: ld returned 1 exit status
> make: *** [/opt/RapidCFD/RapidCFD-dev/platforms/linux64NvccDPOpt/lib/openmpi-1.8.4-cuda/libPstream.so] Error 1

Please find the full log attached.
[log_Allwmake.txt](https://github.com/Atizar/RapidCFD-dev/files/748057/log_Allwmake.txt)

Maybe a symbolic link will help in this case, too?

Thanks a lot!!

**Comment by daniel-jasinski** [comment]
Yes, you need to add similar links to the **lib** directory, so that the linker can find libraries.

**Comment by KingKraut** [comment]
I tried
 ln -s /opt/RapidCFD/ThirdParty-dev/openmpi-1.8.4-cuda/lib /opt/RapidCFD/ThirdParty-dev/platforms/linux64Nvcc/openmpi-1.8.4-cuda/lib
as you suggested and got the following error message
[log_Allwmake_1.txt](https://github.com/Atizar/RapidCFD-dev/files/750400/log_Allwmake_1.txt)
However, just trying to run a simulation in parallel worked. When I ran the Allwmake-script from within src/Pstream again, the error message was gone, too... 
[log_Allwmake_2.txt](https://github.com/Atizar/RapidCFD-dev/files/750404/log_Allwmake_2.txt)
So I don't really know, what the difference was, but I guess the problem is solved! 

Thanks a lot again for all the help and hints!
Looking forward to using RapidCFD on more GPUs and speed up things a little!!

Best regards

**Comment by daniel-jasinski** [comment]
I am glad it works.

Have nice simulations!
