### ISSUE TITLE
const cache instead of texture cache

### ISSUE THREAD

**Issue by TonkomoLLC** [Atizar/RapidCFD-dev#43]
Hello,

In commit #41 we eliminated read-only data cache capabilities for CC>=3.5 in order to allow execution of applications with the -arch_sm_xx flag greater than xx=30.  This speeds up application startup on GPU's with CC > 3.x.

In reviewing this PR, Daniel wrote the following idea:

> I was thinking about this way of resolving the issue of CC >= 3.5 and I think that we could try to keep the const cache access (__ldg instruction) instead of using the texture cache. This would require checking CC version at run-time and skipping creation and destruction of texture object for CC >= 3.5.

I may have implemented part of this idea, but I have not thoroughly tested to warrant a pull request. But I am interested in discussing with anyone interested.  The changes are at [https://github.com/TonkomoLLC/RapidCFD-dev/commit/d48e6509891f84fee18f66cdf1ca505014bc8ea3](url)

Implemented:
- Use of texture cache is disabled in lduMatrix math (i.e., creation and destruction of the texture object is disabled)
- Pointers qualified with "__ restrict __" to indicate they should be read through the read-only cache

Not implemented:
- Use of texture object for CC <=3.5. I am first testing this without the conditional on texture vs. const cache depending on "__ CUDA_ARCH __" value
- I am a little uncertain where to apply the intrinsic "__ ldg" function in place of a normal pointer dereference to force a load to go through the read-only data cache. Is the use of the "__ restrict __" qualified pointers sufficient? 

So far the proposed edits compile and the resulting application executes. 

I welcome advice and feedback.

**Comment by TonkomoLLC** [comment]
Hello,

For reasons I cannot explain, clinking on the embedded link does lead to a page not found error. But if I copy and paste the URL into a browser I can see the commit on my fork of RapidCFD.   You can also try copying and pasting this tinyURL into your browser to get to my commit: [https://tinyurl.com/y6v7xgrs](url)  Again, simply clicking on the link fails, but copy and paste works.

Your feedback on the __restrict __ pointers is very helpful. If you can access the commit, I am interested in your feedback on where the intrinsic __ldg function should be applied. If you do not have time, I will continue to think about this and work it out in time.

**Comment by TonkomoLLC** [comment]
Hello,

I may have figured out where to apply the intrinsic __ldg function.  In addition to the URL above, please look at [https://github.com/TonkomoLLC/RapidCFD-dev/commit/27dfbb054849e2e7b622aa69921f9fd8bd9357ca](url)
You may need to copy and paste the above URL into your browser.

The code compiles and executes with the proposed changes. However, I am interested in feedback on this implementation.

**Comment by daniel-jasinski** [comment]
Since commit [6b40d01](https://github.com/Atizar/RapidCFD-dev/commit/6b40d011d3932a9bf491f3c307808978f7569139)  constant cache is for devices with CC >= 3.5.
