### ISSUE TITLE
Run-time error occurred.

### ISSUE THREAD

**Issue by Fitanium** [Atizar/RapidCFD-dev#44]
I downloaded the code, and finishing the task "Allmake" without error. And then I choose a case named "cavity", and finished the pre-process on my own computer, witch has installed openfoam[OpenFOAM-5.x (see www.OpenFOAM.org)], before uploading the case to the workstation. Then I started "icoFoam" in the case directory. When check the log file, I found the message:

**/*---------------------------------------------------------------------------*\
| RapidCFD by simFlow (sim-flow.com)                                          |
\*---------------------------------------------------------------------------*/
Build  : dev
Exec   : icoFoam
Date   : Jul 05 2018
Time   : 10:57:03
Host   : "ubunte1604-System-Product-Name"
PID    : 12503
Case   : /home/ubunte1604/cavity/cavity
nProcs : 1
sigFpe : Enabling floating point exception trapping (FOAM_SIGFPE).
fileModificationChecking : Monitoring run-time modified files using timeStampMaster
allowSystemOperations : Allowing user-supplied system call operations

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //
Create time

Create mesh for time = 0

Reading transportProperties

--> FOAM FATAL IO ERROR: 
wrong token type - expected word, found on line 18 the punctuation token '['

file: /home/ubunte1604/cavity/cavity/constant/transportProperties.nu at line 18.

    From function operator>>(Istream&, word&)
    in file primitives/strings/word/wordIO.C at line 74.

FOAM exiting**

I have no idea how to handle it. Do you have any advice?

**Comment by Fitanium** [comment]
thank you very much. With your help, I found no errors after running the cavity. However, when I opened the transportProperties file I found OpenFOAM 2.3.0.

Excuse me, is RapidCFD developed based on OpenFOAM 2.3.0?

**Comment by TonkomoLLC** [comment]
Hi, yes, RapidCFD is based on OpenFOAM 2.3.0.
Best,
