### ISSUE TITLE
DynamicMesh

### ISSUE THREAD

**Issue by panch13114** [Atizar/RapidCFD-dev#5]
I and my colleague noticed that lnInclude directory is missing in dynamicFvMesh. Unfortunately due to this error, dynamicMesh is not compiled properly. Could you please add this directory? 
*/opt/RapidCFD-dev/src/dynamicFvMesh has only 8 directories, whereas openfoam has 9

**Comment by daniel-jasinski** [comment]
I pushed a commit correcting this issue.

Please note that some parts of the dynamic mesh functionality still run on the CPU. It requires some work to achieve better performance.
