### ISSUE TITLE
with which version of OF is compatible?

### ISSUE THREAD

**Issue by efirvida** [Atizar/RapidCFD-dev#52]
I´m using the OF6 right now, but I need to speed up my simulations, I don´t find any info about the base version of OF for the RapidCFD.
Rigth now i´m using. pimpleDyMFoam, or pimpleFoam(they combine the 2 solvers in the OF6), with 6dofsolidmotionsolver.   
Is this supported in RapidCFD?

**Comment by TonkomoLLC** [comment]
RapidCFD is forked from [OpemFOAM 2.3](https://openfoam.org/release/2-3-0/).  There are some six degree of freedom developments in this release.

sixDoFRigidBodyMotion appears to be part of the RapidCFD codebase. I am not sure if this is the functionality you need, nor have I tested sixDoF features in RapidCFD... 

I know this is an incomplete answer but I hope it helps you out.

**Comment by efirvida** [comment]
I think that if the propeller and wingMotion tutorials works here, i can use Rapid-CFD, did you have run that tutorials?

**Comment by TonkomoLLC** [comment]
RapidCFD did not come with tutorials. However, I confirm that pimpleDyMFoam is part of the distribution of RapidCFD, and OpenFOAM 2.3.x has tutorials for wingMotion and propeller under the pimpleDymFoam directory.  So hopefully this will work for you. However, I have never personally run the wingMotion or propeller tutorials with RapidCFD. I have, however, used a moving mesh to simulate a mixer with RapidCFD's interDyMFoam.

**Comment by efirvida** [comment]
thanks I will try and let you know
