### ISSUE TITLE
Running RapidCFD on SimFlow

### ISSUE THREAD

**Issue by lolleo12** [Atizar/RapidCFD-dev#66]
Hey,
Is there a possibility of running RapidCFD directly in simflow on windows 10? 
I haven't found anything about that in other forums so I am asking the question myself.
Thanks a lot!

**Comment by daniel-jasinski** [comment]
Unfortunately not.
The only supported CUDA compiler on Windows is MSVC which is not capable of compiling OpenFOAM or RapidCFD.
Maybe in the future we will be able to compile and run RC under WSL on Windows, but for now accessing GPU from WSL is not supported.
