### ISSUE TITLE
Build errors

### ISSUE THREAD

**Issue by paulhandy** [Atizar/RapidCFD-dev#8]
I've seen these errors repeated over and over while building:

```
List.C: error: ‘class Foam::List<int>’ has no member named ‘v_’
VectorSpace.C: error: ‘const class Foam::Vector<double>’ has no member named ‘operator[]
```

**Comment by daniel-jasinski** [comment]
Could you provide information about your GCC and CUDA version?

**Comment by paulhandy** [comment]
gcc version 5.2.0 (GCC) 
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2015 NVIDIA Corporation
Built on Tue_Aug_11_14:27:32_CDT_2015
Cuda compilation tools, release 7.5, V7.5.17

**Comment by daniel-jasinski** [comment]
So far I have not tried building using this version of GCC and CUDA.

Could you send to my email the log from the build, maybe I can figure something out remotely?

**Comment by paulhandy** [comment]
I believe my problem may be stemming from the gpu that I have available at
compile time. It requires sm_11, which nvcc doesn't provide. When I have
access to the gpu that uses sm_30, I will try again and report the results
of that. If that goes well, I will consider this an issue with nvcc support
and not this package.

**Comment by daniel-jasinski** [comment]
I do not think that the available gpu is the reason for this problem, but please let me know if it makes a difference.
