### ISSUE TITLE
thrust::system::system_error

### ISSUE THREAD

**Issue by wangxiaomeng3** [Atizar/RapidCFD-dev#81]
Hi everyone,
I was able to run the simpleFoam solver. However, found some error,

/*---------------------------------------------------------------------------*\
| RapidCFD by simFlow (sim-flow.com)                                          |
\*---------------------------------------------------------------------------*/
Build  : dev
Exec   : mysimpleFoam -case /home/w/Desktop/testCFD
Date   : Jan 20 2021
Time   : 13:07:39
Host   : "w"
PID    : 23267
Case   : /home/w/Desktop/testCFD
nProcs : 1
sigFpe : Floating point exception trapping - not supported on this platform
fileModificationChecking : Monitoring run-time modified files using timeStampMaster
allowSystemOperations : Allowing user-supplied system call operations

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //
Create time

...
Time = 10

smoothSolver:  Solving for Ux, Initial residual = 0.0359738, Final residual = 0.0188789, No Iterations 1000
smoothSolver:  Solving for Uy, Initial residual = 0.0425125, Final residual = 0.0193534, No Iterations 1000
smoothSolver:  Solving for Uz, Initial residual = 0.0508246, Final residual = 0.0194308, No Iterations 1000
GAMG:  Solving for p, Initial residual = 0.157222, Final residual = 0.00880482, No Iterations 3
time step continuity errors : sum local = 30.7828, global = -0.131664, cumulative = -0.193272
ExecutionTime = 42.37 s  ClockTime = 43 s

End

terminate called after throwing an instance of 'thrust::system::system_error'
  what():  CUDA free failed: cudaErrorCudartUnloading: driver shutting down
Aborted (core dumped)

-----------------------------------------------------------------------------------------------------------------------------------------------------
Hardware I'm currently testing it at is a GeForce GTX 1060 6GB, driver version is 390.48. 
Ubuntu 18.04.1 LTS

**terminate called after throwing an instance of 'thrust::system::system_error'
  what():  CUDA free failed: cudaErrorCudartUnloading: driver shutting down
Aborted (core dumped)**

Thanks for your help.

**Comment by wangxiaomeng3** [comment]
Thanks, TonkomoLLC, for the quick reply. 
For sure, I have modified it from sm_30 to sm_61, so it can compile pass. 
I tried sm_61 and sm_60 compile finish.However it throw the same error ,when run "simpleFoam" solver .

Best regards,

**Comment by TonkomoLLC** [comment]
Maybe the error is related to [this issue/solution](https://github.com/Atizar/RapidCFD-dev/issues/59#issuecomment-487136615). To recap the discussion at the linked thread, a thrust error thrown at the end of a case may be related to an error thrown in `malloc_and_free.h`. Solving this requires commenting out the referenced error and then completely recompiling RapidCFD. I am not sure if this will solve your issue, but it may be worth a try if your error is occurring at the end of a run.
Good luck and best regards,
Eric

**Comment by wangxiaomeng3** [comment]
thanks, it can run without the issue  , although it just  comment out the referenced error.
