### ISSUE TITLE
No Iterations 1000，It runs very slowly

### ISSUE THREAD

**Issue by wangxiaomeng3** [Atizar/RapidCFD-dev#83]
Hi everyone,
I was able to run the simpleFoam solver. However, found some error ,and It runs very slowly

/---------------------------------------------------------------------------
| RapidCFD by simFlow (sim-flow.com) |
*---------------------------------------------------------------------------*/
Build : dev
Exec : mysimpleFoam -case /home/w/Desktop/testCFD
Date : Jan 20 2021
Time : 13:07:39
Host : "w"
PID : 23267
Case : /home/w/Desktop/testCFD
nProcs : 1
sigFpe : Floating point exception trapping - not supported on this platform
fileModificationChecking : Monitoring run-time modified files using timeStampMaster
allowSystemOperations : Allowing user-supplied system call operations

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //
Create time

...
Time = 10

smoothSolver: Solving for Ux, Initial residual = 0.0359738, Final residual = 0.0188789, **No Iterations 1000**
smoothSolver: Solving for Uy, Initial residual = 0.0425125, Final residual = 0.0193534, **No Iterations 1000**
smoothSolver: Solving for Uz, Initial residual = 0.0508246, Final residual = 0.0194308, **No Iterations 1000**
GAMG: Solving for p, Initial residual = 0.157222, Final residual = 0.00880482, No Iterations 3
time step continuity errors : sum local = 30.7828, global = -0.131664, cumulative = -0.193272
ExecutionTime = 42.37 s ClockTime = 43 s

End

terminate called after throwing an instance of 'thrust::system::system_error'
what(): CUDA free failed: cudaErrorCudartUnloading: driver shutting down
Aborted (core dumped)
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------

Hardware I'm currently testing it at is a GeForce GTX 1060 6GB, driver version is 390.48.
Ubuntu 18.04.1 LTS

...No Iterations 1000
...No Iterations 1000
...No Iterations 1000

It runs very slowly,how to reduce value for "No Iterations" 

Thanks for your help.

**Comment by TonkomoLLC** [comment]
Hi,
You can reduce the number of iterations in `fvSolution` following the same method of setting `maxIter` as per the [normal OpenFOAM method](https://cfd.direct/openfoam/user-guide/v6-fvsolution/). That is, in fvSolution, you can set maxIter for each set of solvers:

```
    p 
    { 
        solver          PCG; 
        preconditioner  DIC; 
        tolerance       1e-06;
       maxIter       1000;  // defaults to 1000, set to whatever you want 
        relTol          0.05; 
    } 
```

If you are having problems with RapidCFD and want to discriminate between your specific case and your RapidCFD setup, you can try some of the test cases [here](https://github.com/TonkomoLLC/RapidCFD-Tests).  Also, you can try converting an OpenFOAM-2.3.x tutorial that uses simpleFoam to RapidCFD and see if that works. I'm guessing if you got this far it's probably some characteristic of your case, grid, settings, etc. that is causing the difficulty with the solution, but I cannot say this with certainty. 

Good luck with your troubleshooting.

Best regards,

Eric

**Comment by wangxiaomeng3** [comment]
Hello Eric,

Thank you for your help, the issue has been solved.

Best regards,
