### ISSUE TITLE
sigFpe: Floating point exception trapping

### ISSUE THREAD

**Issue by Flowier** [Atizar/RapidCFD-dev#85]
Hello :) 

@TonkomoLLC  great help here on the issues page. Already helped me out :) 

after changing my GPU and compiling from scratch i get the following Issue: 

```
sigFpe : Floating point exception trapping - not supported on this platform
fileModificationChecking : Monitoring run-time modified files using timeStampMaster
allowSystemOperations : Allowing user-supplied system call operations
```

I did not find anything on the internet. Do you have any thoughts on that error? 

Best wishes 
Ingo

**Comment by TonkomoLLC** [comment]
Dear Ingo, 

Thanks for the kind words.

The text you highlighted is normal, I think. The banner shown at the start of a normal Rapid-CFD run shows these messages:

```
/*---------------------------------------------------------------------------*\
| RapidCFD by simFlow (sim-flow.com)                                          |
\*---------------------------------------------------------------------------*/
Build  : rapid-0fc3af285e35
Exec   : icoFoam
Date   : Jun 18 2021
Time   : 06:25:05
Host   : "aris"
PID    : 2168046
Case   : /home/eadaymo/RapidCFD/eadaymo-rapid/run/RapidCFD-Tests/cavity
nProcs : 1
sigFpe : Floating point exception trapping - not supported on this platform
fileModificationChecking : Monitoring run-time modified files using timeStampMaster
allowSystemOperations : Allowing user-supplied system call operations

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //
```

I do not think that the text you highlighted is an error.  However, if you are implying that immediately after these messages are displayed the solver crashes, and if RapidCFD worked before the GPU change, then please confirm that when you recompiled you changed the rules in `$WM_PROJECT_DIR/wmake/rules/linux64Nvcc/c++` and`$WM_PROJECT_DIR/wmake/rules/linux64Nvcc/c`, so these files are updated with the -arch=sm_## flag that is appropriate for your new GPU. You can find the appropriate -arch=sm_## value on the internet: one example is [here](https://arnon.dk/matching-sm-architectures-arch-and-gencode-for-various-nvidia-cards/). 

I hope this clue is helpful for your troubleshooting.

Best regards,

Eric

**Comment by Flowier** [comment]
Actually you are right, the crash was some other error, i just assumed that this is the error.
Thanks for your fast reply! :) 

Why is is it not fully calculating on the GPU? My CPU is on 100% usage all the time and GPU is at 70-80% (i think because of data transfer). Can't it use only GPU, so i can work with e.g. a meshing program on the CPU?
Did i not install something properly or is it the way it is?

Thanks in advance :)

**Comment by TonkomoLLC** [comment]
Dear Ingo,

I think it is normal for one core to be used @ 100% usage. To the best of my knowledge, the linear solvers are utilizing the GPU, but some operations still take place on the CPU. For example, if you look at the source code of the solvers (like `pisoFoam`), the code is written in C++ for the CPU. So I think it is OK that one CPU is used, since the entire code base is not designed to execute only on a GPU. 

Typically computers have multi-cores, so if one core is utilized by `RapidCFD`, hopefully you have other cores available on your computer to handle other tasks, like meshing.

Hope this feedback helps.

Cheers,

Eric

**Comment by Flowier** [comment]
Oh i see, i just put "top" into terminal which says that the process pisoFoam had 99% cpu usage. 
I missed the fact that this is only one core. So i can run cfMesh which is multithreading parallely :)

Thanks again and sorry for that "simple misses" i had :)
